name: PC Nightly Build

on:
  push:
    paths:
      - CMakeLists.txt
      - source/runtime/**
      - source/renderers/sdl2/**
      - source/renderers/opengl/**
      - source/renderers/headless/**
      - source/windowing/sdl2/**
      - source/windowing/glfw/**
      - source/windowing/headless/**
      - source/*
      - source/menus/**
      - source/audio/sdl2/**
      - source/audio/sdl3/**
      - source/audio/headless/**
      - gfx/menu/**
      - include/**
      - .github/workflows/nightly-pc.yml
      - docker/Dockerfile.linux
      - docker/Dockerfile.windows
      - docker/Dockerfile.macos
      - source/main.cpp
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  linux:
    name: Linux x86_64 SDL2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Export
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile.linux
          target: exporter
          outputs: type=local,dest=.

      - name: Upload Artifact
        if: github.event_name != 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: Scratch Everywhere! Linux Nightly
          path: scratch-everywhere
  linux-sdl1:
    name: Linux x86_64 SDL1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Export
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile.linux
          target: exporter
          outputs: type=local,dest=.
          build-args: |
            RENDERER=sdl1
            WINDOWING=sdl1
            AUDIO_ENGINE=sdl1

      - name: Upload Artifact
        if: github.event_name != 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: Scratch Everywhere! Linux SDL1 Nightly
          path: scratch-everywhere
  linux-headless:
    name: Linux x86_64 Headless
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Export
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile.linux
          target: exporter
          outputs: type=local,dest=.
          build-args: |
            RENDERER=headless
            WINDOWING=headless
            AUDIO_ENGINE=headless

      - name: Upload Artifact
        if: github.event_name != 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: Scratch Everywhere! Linux Headless Nightly
          path: scratch-everywhere
  linux-opengl:
    name: Linux x86_64 OpenGL
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Export
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile.linux
          target: exporter
          outputs: type=local,dest=.
          build-args: |
            RENDERER=opengl
            WINDOWING=glfw
            AUDIO_ENGINE=sdl3
            EXT_ARGS=-DSDL_WAYLAND=OFF

      - name: Upload Artifact
        if: github.event_name != 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: Scratch Everywhere! Linux OpenGL Nightly
          path: scratch-everywhere
  windows:
    name: Windows x86_64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Export
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile.windows
          target: exporter
          outputs: type=local,dest=.

      - name: Upload Artifact
        if: github.event_name != 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: Scratch Everywhere! Windows Nightly
          path: scratch-everywhere.exe
  macos-intel:
    name: macOS x86_64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Export
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile.macos
          target: exporter
          outputs: type=local,dest=.

      - name: Upload Artifact
        if: github.event_name != 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: Scratch Everywhere! macOS x86_64 Nightly
          path: scratch-everywhere
  macos-arm:
    name: macOS ARM64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Export
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile.macos
          target: exporter
          outputs: type=local,dest=.
          build-args: ARCH=arm64

      - name: Upload Artifact
        if: github.event_name != 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: Scratch Everywhere! macOS ARM64 Nightly
          path: scratch-everywhere
  macos-universal:
    name: macOS Universal
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    needs: [macos-arm, macos-intel]
    steps:
      - name: Download Intel Artifact
        uses: actions/download-artifact@v4
        with:
          name: Scratch Everywhere! macOS x86_64 Nightly
          path: intel-build
      - name: Download ARM Artifact
        uses: actions/download-artifact@v4
        with:
          name: Scratch Everywhere! macOS ARM64 Nightly
          path: arm-build
      - name: Download and Prepare lipo
        run: |
          curl -L -o lipo https://github.com/konoui/lipo/releases/download/v0.9.4/lipo_linux_amd64
          chmod +x lipo
      - name: Create Universal Binary
        run: ./lipo -output scratch-everywhere -create arm-build/scratch-everywhere intel-build/scratch-everywhere
      - name: Upload Artifact
        if: github.event_name != 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: Scratch Everywhere! macOS Universal Nightly
          path: scratch-everywhere
